bounswe/bounswe2024group7

- artifact_backend/artifactapp/search.py
- artifact_backend/artifactapp/urls.py
- artifact_backend/artifactapp/views.py
> Created search endpoint

- artifact_backend/artifactapp/views.py
- artifact_backend/requirements.txt
* **Please check if the PR fulfills these requirements**
- Add `SPARKQLWrapper` to requirements.txt
- Add `status.HTTP_STATUS_CODE` to Response objects as second parameter.
We do not get any error after running the `docker-compose up command`
> fix module not found error and update status

- artifact_backend/artifactapp/urls.py
- frontend/src/components/RegisterComponent.component.jsx
- frontend/src/components/SearchBar.component.jsx
- frontend/src/components/loginCard.component.jsx
- frontend/src/components/navigationResponsive.component.jsx
- frontend/src/routes/__root.jsx
- frontend/src/routes/login.jsx
- frontend/src/routes/register.jsx
* **Please check if the PR fulfills these requirements**
- Add SearchBar component to navigation as a responsive component.
- Save the result of a search to cookies.
- Show error dialog when the request throws an error.
- Remove trailing "/" from `urls.py`
> add search bar and get response

- frontend/README.md
- frontend/vite.config.js
Created the README.MD file for the frontend application. This file includes design choices, run instructions, and deployment suggestions.
> Create README.MD for the Frontend application

- artifact_MobileApp/Api.js
- artifact_MobileApp/App.js
- artifact_MobileApp/AuthContext.js
- artifact_MobileApp/Home.js
- artifact_MobileApp/Login.js
- artifact_MobileApp/SearchBar.js
- artifact_MobileApp/Signup.js
- artifact_MobileApp/package-lock.json
- artifact_MobileApp/package.json
- artifact_backend/artifact/settings.py
implemented login and signup to mobile parts.
important notes to check:
-the functions for login and signup are added but backend cors should be changed accordingly.
-Mobile part now has logout button, username info on navigation bar.
-Login and signup components have links to eachother.
-Errors on login or signup now shows a popup with raised error
> 74 connect mobile apps functions to backend

- artifact_backend/artifactapp/search.py
- artifact_backend/artifactapp/views/auth.py
- artifact_backend/artifactapp/views/search.py
- artifact_backend/requirements.txt
- frontend/src/components/searchResults.component.jsx
users can search for a genre, painting, and users can see all the paintings related with most relevant results
> 117 implementing new search method

- backend/demo-group7/src/main/java/com/group7/demo/configs/SecurityConfiguration.java
- backend/demo-group7/src/main/java/com/group7/demo/configs/SessionAuthenticationFilter.java
- backend/demo-group7/src/main/java/com/group7/demo/controllers/AuthenticationController.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/LoginRequest.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/LoginResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/RegisterRequest.java
- backend/demo-group7/src/main/java/com/group7/demo/models/Role.java
- backend/demo-group7/src/main/java/com/group7/demo/models/User.java
- backend/demo-group7/src/main/java/com/group7/demo/repository/UserRepository.java
- backend/demo-group7/src/main/java/com/group7/demo/services/AuthenticationService.java
Created login, register and logout endpoints.
Here is the flow:
* You register from /auth/register endpoint.
* /auth/login endpoint returns a token.
* Every other endpoint requires a header for authentication. Header's key is "Token" and value is what login endpoint returns. Header is checked for every request except for login and register.
* /auth/logout?sessionToken=xxxxxx endpoint deletes the token from database and unauthenticate the user.
> Issue#145 create authorization endpoints

- backend/demo-group7/src/main/java/com/group7/demo/configs/SecurityConfiguration.java
- backend/demo-group7/src/main/java/com/group7/demo/controllers/AuthenticationController.java
- backend/demo-group7/src/main/java/com/group7/demo/controllers/UserController.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/UserProfileResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/models/User.java
- backend/demo-group7/src/main/java/com/group7/demo/services/AuthenticationService.java
- backend/demo-group7/src/main/java/com/group7/demo/services/UserService.java
Created user related endpoints.
* GET /api/user/{username} returns user details (username, fullname, role, followers and following). After post, comment and like entity is created it will return them as well. Doesn't require authentication.
* GET /api/user/{username}/followers endpoint returns the usernames of the followers for that user. Doesn't require authentication.
* GET /api/user/{username}/following endpoint returns the usernames of the users that specified user folllow. Doesn't require authentication.
* POST /api/user/{userToFollow}/follow endpoint follows the userToFollow for authenticated user. Requires authentication header.
* DELETE /api/user/{userToUnfollow}/follow endpoint unfollows the userToUnfollow for authenticated user. Requires authentication header.
* GET /auth/user …
> Issue#153 create profile endpoints

- backend/demo-group7/src/main/java/com/group7/demo/controllers/PostController.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/PostRequest.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/PostResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/models/Post.java
- backend/demo-group7/src/main/java/com/group7/demo/models/User.java
- backend/demo-group7/src/main/java/com/group7/demo/repository/PostRepository.java
- backend/demo-group7/src/main/java/com/group7/demo/services/PostService.java
Relating created Posts with user-id, addition over PR #152
> Relate created post with userId

- backend/demo-group7/src/main/java/com/group7/demo/configs/SecurityConfiguration.java
- backend/demo-group7/src/main/java/com/group7/demo/controllers/PostController.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/PostRequest.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/PostResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/repository/PostRepository.java
- backend/demo-group7/src/main/java/com/group7/demo/services/AuthenticationService.java
- backend/demo-group7/src/main/java/com/group7/demo/services/PostService.java
- backend/demo-group7/src/main/java/com/group7/demo/services/UserService.java
- frontend/src/context/PostContext.jsx
Created endpoint: GET /api/posts/random?count=x to get random posts. This endpoint doesn't require authentication.
Refactored post endpoints. You should not send user id when creating a post from now on, the user is decided from authentication header.  Delete post endpoint checks if the authenticated user is the owner of the post.
> Issue#162 create endpoint to get random posts

- frontend/src/components/navigationResponsive.component.jsx
- frontend/src/components/profilePage.component.jsx
- frontend/src/constants/paths.js
- frontend/src/context/UserContext.jsx
- frontend/src/main.jsx
- frontend/src/routes/profile.jsx
* **Please check if the PR fulfills these requirements**
Feature update
User can't view their profile page
User can view their profile page
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No
> added profile page on web

- backend/demo-group7/src/main/java/com/group7/demo/controllers/PostController.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/UserProfileResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/repository/PostRepository.java
- backend/demo-group7/src/main/java/com/group7/demo/services/PostService.java
- backend/demo-group7/src/main/java/com/group7/demo/services/UserService.java
* GET /api/user/{username} endpoint now returns posts of that user as well
* Created new endpoint: GET /api/posts/user/{username} returns posts belonging to that user. Requires authentication (can be changed).
> Issue#166 return posts of specific user

- backend/demo-group7/src/main/java/com/group7/demo/controllers/TrainingProgramController.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/ExerciseDetailRequest.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/ExerciseDetailResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/ExerciseRequest.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/ExerciseResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/TrainingProgramRequest.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/TrainingProgramResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/models/Exercise.java
- backend/demo-group7/src/main/java/com/group7/demo/models/ExerciseDetail.java
- backend/demo-group7/src/main/java/com/group7/demo/models/TrainingProgram.java
- backend/demo-group7/src/main/java/com/group7/demo/models/User.java
- backend/demo-group7/src/main/java/com/group7/demo/models/enums/LocationType.java
- backend/demo-group7/src/main/java/com/group7/demo/models/enums/MuscleGroup.java
- backend/demo-group7/src/main/java/com/group7/demo/models/enums/ProgramType.java
- backend/demo-group7/src/main/java/com/group7/demo/repository/ExerciseRepository.java
- backend/demo-group7/src/main/java/com/group7/demo/repository/TrainingProgramRepository.java
- backend/demo-group7/src/main/java/com/group7/demo/services/TrainingProgramService.java
This PR implements the "Create Training Program" functionality, allowing trainers to create structured training programs. The endpoint allows trainers to define program details, including exercises, sets, repetitions, and the targeted muscle groups.
- Adds a new API endpoint `/api/training-programs` to allow **trainers** to create training programs.
- The created training program includes:
- Title
- Program type (e.g., Group, Individual)
- Location type (e.g., Home, Gym, Outdoor)
- List of exercises with details (name, muscle group, sets, repetitions)
- Description
> Issue#160 create training program

- backend/demo-group7/src/main/java/com/group7/demo/controllers/TrainingProgramController.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/TrainingProgramRequest.java
- backend/demo-group7/src/main/java/com/group7/demo/services/TrainingProgramService.java
Added validation for creating/deleting programs. Made sure user that creates the program is trainer. And user who deletes the program is the owner.
> Added validation and authentication for creating and deleting programs

- backend/demo-group7/src/main/java/com/group7/demo/controllers/TrainingProgramController.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/UserProfileResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/repository/TrainingProgramRepository.java
- backend/demo-group7/src/main/java/com/group7/demo/services/TrainingProgramService.java
- backend/demo-group7/src/main/java/com/group7/demo/services/UserService.java
* Created new endpoint to get training programs by trainier: GET /api/training-programs/trainer/{username}
* GET /api/user/{username} now also returns created training programs if there are any.
> Issue#173 create endpoint for getting training program for user

- backend/demo-group7/src/main/java/com/group7/demo/controllers/TrainingProgramController.java
- backend/demo-group7/src/main/java/com/group7/demo/controllers/UserController.java
- backend/demo-group7/src/main/java/com/group7/demo/models/TrainingProgram.java
- backend/demo-group7/src/main/java/com/group7/demo/models/User.java
- backend/demo-group7/src/main/java/com/group7/demo/models/UserTrainingProgram.java
- backend/demo-group7/src/main/java/com/group7/demo/repository/UserTrainingProgramRepository.java
- backend/demo-group7/src/main/java/com/group7/demo/services/TrainingProgramService.java
- backend/demo-group7/src/main/resources/application.properties
This PR introduces an endpoint for authenticated users to join a training program. Users can join a program via the `/programs/{programId}/join` endpoint.
> Join Training Program Endpoint

- mobile/Api.js
- mobile/components/Login.js
- mobile/components/Register.js
- mobile/package-lock.json
- mobile/package.json
* **Please check if the PR fulfills these requirements**
Enhancement of existing features
Login and register pages are connected with backend endpoints where it works flawlessly with the usage of axios request
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Mock data creation in the demo can be changed due to this update
> Connected Login and Register with backend

- backend/demo-group7/src/main/java/com/group7/demo/dtos/PostRequest.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/PostResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/mapper/CustomerMapper.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/mapper/Mapper.java
- backend/demo-group7/src/main/java/com/group7/demo/models/Post.java
- backend/demo-group7/src/main/java/com/group7/demo/repository/UserRepository.java
- backend/demo-group7/src/main/java/com/group7/demo/services/PostService.java
- backend/demo-group7/src/main/java/com/group7/demo/services/TrainingProgramService.java
- backend/demo-group7/src/main/java/com/group7/demo/services/UserService.java
* Moved mappers to separate class.
* Changed content field of Post model to large object.
* Added optional training program field to Post model. In the request, training program id will be sent optionally. In the post responses, whole training program object will be returned.
* Added transactional to some methods to avoid errors about large object retrieval from db.
> Issue#203 share training program in posts

- frontend/src/context/AppContext.jsx
- frontend/src/routes/__root.jsx
Create AppContext and add get exercises endpoint to it. Now exercises is reachable in any component of our app.
> Issue#212 Add AppContext and return Exercises

- backend/demo-group7/src/main/java/com/group7/demo/controllers/TrainingProgramController.java
- backend/demo-group7/src/main/java/com/group7/demo/services/TrainingProgramService.java
Added response body for the updated training program for these endpoints:
- `/{trainingProgramId}/leave`
- `/{trainingProgramId}/join`
- `/{trainingProgramId}/exercises/{exerciseId}/complete`
- `/{trainingProgramId}/exercises/{exerciseId}/uncomplete`
- `/{trainingProgramId}/complete`
> Add modified training programs in the response for tracking endpoints

- backend/demo-group7/src/main/java/com/group7/demo/controllers/TagController.java
- backend/demo-group7/src/main/java/com/group7/demo/repository/TagRepository.java
- backend/demo-group7/src/main/java/com/group7/demo/services/TagService.java
New endpoint to retrive all tags, GET /api/tags
> Add Tag Endpoint

- backend/demo-group7/src/main/java/com/group7/demo/controllers/TrainingProgramController.java
- backend/demo-group7/src/main/java/com/group7/demo/repository/UserTrainingProgramRepository.java
- backend/demo-group7/src/main/java/com/group7/demo/services/TrainingProgramService.java
Refactored already ongoing training program checks
> Refactor training program tracking mechanism

- mobile/components/Create.js
- mobile/components/CreateDietProgram.js
- mobile/components/CreatePost.js
- mobile/components/CreateProgram.js
- mobile/components/Home.js
CreatePost is connected with backend
> Connect CreatePost with backend

- backend/demo-group7/src/main/java/com/group7/demo/dtos/TrainingProgramRequest.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/TrainingProgramResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/WeekRequest.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/WeekResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/WorkoutExerciseRequest.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/WorkoutExerciseResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/WorkoutRequest.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/WorkoutResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/mapper/Mapper.java
- backend/demo-group7/src/main/java/com/group7/demo/models/TrainingProgram.java
- backend/demo-group7/src/main/java/com/group7/demo/models/Week.java
- backend/demo-group7/src/main/java/com/group7/demo/models/Workout.java
- backend/demo-group7/src/main/java/com/group7/demo/models/WorkoutExercise.java
- backend/demo-group7/src/main/java/com/group7/demo/models/enums/ProgramLevel.java
- backend/demo-group7/src/main/java/com/group7/demo/models/enums/ProgramType.java
- backend/demo-group7/src/main/java/com/group7/demo/services/TrainingProgramService.java
- Created new models:
- Week (Training Program Week)
- Workout
- WorkoutExercise
- ProgramLevel enum (enum values should be changed)
- ProgramType enum (enum values should be changed)
- Updated TrainingProgram model based on new models.
- Created new DTOs based on new models.
- Updated mappers
- Updated some functions in TrainingProgramService
Note that these changes are about the training program that trainer creates. In other words, it has no tracking elements. In the next steps we should add tracking elements. I commented out some of the functions in the TrainingProgramService to avoid compilation errors. These functions will change when we implement new tracking mechanisms.
Example request to create a new training program:
```json
{
"title": "Full Body Strength Program", …
```
> Issue#261 Change Training Program Model

- backend/demo-group7/src/main/java/com/group7/demo/controllers/TrainingProgramController.java
- backend/demo-group7/src/main/java/com/group7/demo/repository/WorkoutExerciseWithTrackingRepository.java
- backend/demo-group7/src/main/java/com/group7/demo/services/TrainingProgramService.java
* Created `/api/training-programs/{programId}/workout-exercises/{workoutExerciseId}/complete` endpoint.
* This endpoints takes an array of integers in the request body.
* It checks if the length of the array in the request body matches with the number of sets of the exercise.
* It also checks if that exercise is valid for completion. User cannot complete exercise in one workout without completing previous workouts first. But in the current workout, user is free to complete the exercises in any order.
Path: `/api/training-programs/10/workout-exercises/87/complete`
Body: `[10,12,13]`
```json
{
"id": 10,
"title": "Full Body Strength Program",
"description": "A comprehensive full-body strength training program for intermediate level.",
"trainer": "oguzhekim1",
"type": "BODY_BUILDING", …
```
> Created complete exercise endpoint

- backend/demo-group7/src/main/java/com/group7/demo/configs/SecurityConfiguration.java
- backend/demo-group7/src/main/java/com/group7/demo/controllers/ExerciseController.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/ExerciseProgress.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/ExerciseProgressResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/repository/WorkoutExerciseWithTrackingRepository.java
- backend/demo-group7/src/main/java/com/group7/demo/services/ExerciseService.java
* Created endpoint to track authenticated user's progress on a certain exercise. As a result, this endpoint requires authentication.
`GET` `/api/exercises/6/progress` (with authentication header)
```json
{
"exercise": {
"id": 6,
"name": "alternate heel touchers",
"gifUrl": "https://v2.exercisedb.io/image/oEDks76vGn0yTF",
"bodyPart": "WAIST",
"targetMuscle": "ABS",
"equipment": "BODY_WEIGHT",
"instructions": [
"Lie flat on your back with your knees bent and feet flat on the ground.",
"Extend your arms straight out to the sides, parallel to the ground.",
"Engaging your abs, lift your shoulders off the ground and reach your right hand towards your right heel.",
"Return to the starting position and repeat on the left side, reaching your left hand towards your left heel.",
"Continue …
```
> Issue#276 endpoint for exercise based progress over time

- backend/demo-group7/.gitignore
- backend/demo-group7/src/main/java/com/group7/demo/controllers/FeedbackController.java
- backend/demo-group7/src/main/java/com/group7/demo/controllers/SearchController.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/FeedbackRequest.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/FeedbackResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/mapper/Mapper.java
- backend/demo-group7/src/main/java/com/group7/demo/models/Feedback.java
- backend/demo-group7/src/main/java/com/group7/demo/repository/FeedbackRepository.java
- backend/demo-group7/src/main/java/com/group7/demo/services/FeedbackService.java
- backend/demo-group7/src/main/java/com/group7/demo/services/SearchService.java
- backend/demo-group7/src/main/resources/application.properties
Added feedback endpoints to enable users to provide and retrieve feedback:
- **POST `/api/feedback`**: Submit feedback for a training program.
- **GET `/api/feedback/training-program/{id}`**: Retrieve feedback for a specific training program.
- **GET `/api/feedback/user/{id}`**: Retrieve feedback submitted by a specific user. 
Responses are now streamlined using `FeedbackResponse` DTO to avoid recursion and return meaningful data.
Example body for POST feedback:
{
"trainingProgramId": 1,
"userId": 1,
"bodyPart": "CHEST",
"weekNumber": 1,
"workoutNumber": 3,
"exerciseNumber": 5,
"feedbackText": "This exercise really helped improve my chest strength."
}
Example response for GET Feedback:
{
"id": 6,
"trainingProgramTitle": "Full Body Strength Program",
"username": "test",
"bodyPart": …
> Add Feedback Service 

- mobile/App.js
- mobile/components/Feed.js
- mobile/components/Home.js
- mobile/components/JoinedWeek.js
- mobile/components/JoinedWorkout.js
- mobile/components/Login.js
- mobile/components/PostCard.js
- mobile/components/PostDetail.js
- mobile/components/ProgramCard.js
- mobile/components/ProgramDetail.js
- mobile/components/UserProfile.js
- mobile/components/WorkoutDetails.js
- mobile/user.js
Feature and bug fix
Logout doesn't work properly, follow&unfollow&like&unlike is not connected to backend. Training program structure is not suitable for the new design & response format from endpoints
Logout works properly, follow&unfollow&like&unlike are connected to backend. Training program structure is updated according to the new design & response format from endpoints with the introduction of WorkoutDetails, JoinedWeek, JoinedWorkout components and updates in ProgramDetail component.
> Add New Training Program Structure to Mobile

- mobile/App.js
- mobile/components/JoinedExercise.js
- mobile/components/JoinedProgramDetail.js
- mobile/components/JoinedWorkout.js
- mobile/components/ProgramCard.js
Feature
Exercise details page doesn't exist for joined programs therefore users can't complete exercises. Also, a separate display of program is needed for unjoined training programs.
Exercise details page is created so that users can enter completed repetition count to set fields in order to complete exercises. Also, a separate display of program is created for unjoined programs.
> Add exercise detail

- backend/demo-group7/src/main/java/com/group7/demo/controllers/SurveyController.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/SurveyRequest.java
- backend/demo-group7/src/main/java/com/group7/demo/repository/UserRepository.java
- backend/demo-group7/src/main/java/com/group7/demo/services/SurveyService.java
Changed survey identifer to username from userid in request bodies or query parameters
GET /api/surveys/user/{userId} -> GET /api/surveys/user/{username}
same changes in POST bodies and query parameters
> Change Survey Identifier to username

- backend/demo-group7/src/main/java/com/group7/demo/controllers/TrainingProgramController.java
- backend/demo-group7/src/main/java/com/group7/demo/models/TrainingProgramRating.java
- backend/demo-group7/src/main/java/com/group7/demo/repository/TrainingProgramRatingRepository.java
- backend/demo-group7/src/main/java/com/group7/demo/repository/TrainingProgramWithTrackingRepository.java
- backend/demo-group7/src/main/java/com/group7/demo/services/TrainingProgramService.java
a feature that allows participants of a training program to rate the program. Users can submit or update their ratings, with ratings restricted to integers between 0 and 5. The average rating (rating) and the total number of ratings (ratingCount) for each training program are dynamically calculated and updated. Only participants of the program can submit ratings.
POST /api/training-programs/{trainingProgramId}/rate?userId={userId}&rating={rating}
example:
POST /api/training-programs/1/rate?userId=123&rating=4
> Add trainign program rating mechanism

- mobile/components/Home.js
- mobile/components/ProfilePage.js
- mobile/components/ProgressTracker.js
- mobile/package-lock.json
- mobile/package.json
This PR introduces an enhancement in progress tracking in the mobile application, which is a progress graph which improves user experience.
A graph indicating progress could be seen from progress tracking page as mentioned in the [related issue](https://github.com/bounswe/bounswe2024group7/issues/292)
A graph indicating progress could be seen from progress tracking page as mentioned in the [related issue](https://github.com/bounswe/bounswe2024group7/issues/292)
This PR does not introduce any breaking changes
> Progress Graph Added

- mobile/components/CreateProgram.js
- mobile/components/common/SpinboxInput.js
Feature
Trainers can't create a program currently. The connection with backend is not established. Additionally, the training program creation input fields are outdated and don't match with the current response format. 
New component reflects the necessary input fields with a dynamic addition / removal of variable count fields such as weeks, workouts, exercises along with a modal that will be used to select exercises. Backend connection is also established.
> Update create program

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/RegisterComponent.component.jsx
- frontend/src/components/navigationResponsive.component.jsx
Users should select their level on fitness and interest areas.
> Add interest areas and level to user register

- mobile/components/CreatePost.js
- mobile/components/Feed.js
- mobile/components/PostCard.js
- mobile/components/PostDetail.js
- mobile/components/ProfilePage.js
- mobile/components/UserProfile.js
This PR introduces a feature reqyest, which is a correct post creation in this renewed mechanism.
Training Programs are attached to the post crating page
No, it does not introduce a breaking change.
> Training Program Added

- mobile/App.js
- mobile/components/JoinedProgramCard.js
- mobile/components/JoinedProgramDetail.js
- mobile/components/JoinedWeek.js
- mobile/components/JoinedWorkout.js
- mobile/components/ProfilePage.js
- mobile/package-lock.json
- mobile/package.json
Feature
Users can't see the updated progress of workouts and weeks. They also can reenter a completed exercise and submit progress
JoinedWorkout and JoinedWeek pages are updated and progresses are connected to backend. Necessary control to prevent resubmitting progress for a previously completed exercise is applied.
> Connect workout and week progress

- backend/demo-group7/src/main/java/com/group7/demo/configs/SecurityConfiguration.java
- backend/demo-group7/src/main/java/com/group7/demo/controllers/TrainingProgramController.java
- backend/demo-group7/src/main/java/com/group7/demo/services/TrainingProgramService.java
Implemented requested changes in [Issue#327](https://github.com/bounswe/bounswe2024group7/issues/327).
> Issue#327 create new endpoints for training programs

- backend/demo-group7/src/main/java/com/group7/demo/dtos/TrainingProgramWithTrackingResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/WeekWithTrackingResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/WorkoutWithTrackingResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/mapper/Mapper.java
Added "completionPercentage" field to TrainingProgramWithTracking response for training program, week and workout. It is calculated based on how many exercises that program/week/workout have and how many of them are completed. The formula can be changed later if wanted. 
Example response when a exercise is completed:
```json
{
"id": 11,
"trackingId": 7,
"title": "Full Body Strength Program",
"description": "A comprehensive full-body strength training program for intermediate level.",
"trainer": "oguzhekim1",
"type": "BODY_BUILDING",
"level": "INTERMEDIATE",
"interval": 2,
"rating": 0.0,
"ratingCount": 0,
"createdAt": "2024-12-13T15:35:49.938353",
"status": "ONGOING",
"joinedAt": "2024-12-15T18:35:00.58951",
"completedAt": null,
"completionPercentage": 80.0,
"lastCompletedWorkoutDate": …
```
> Add completion percentage to training program response

- backend/demo-group7/src/main/java/com/group7/demo/dtos/FeedbackRequest.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/FeedbackResponse.java
- backend/demo-group7/src/main/java/com/group7/demo/dtos/mapper/Mapper.java
- backend/demo-group7/src/main/java/com/group7/demo/models/Feedback.java
- backend/demo-group7/src/main/java/com/group7/demo/models/enums/FeedbackMuscle.java
- backend/demo-group7/src/main/java/com/group7/demo/services/FeedbackService.java
Changed muscle groups for feedback to match the muscle groups in frontend. Groups are these:
```
TRAPEZIUS,
UPPER_BACK,
LOWER_BACK,
CHEST,
BICEPS,
TRICEPS,
FOREARM,
BACK_DELTOIDS,
FRONT_DELTOIDS,
ABS,
OBLIQUES,
ADDUCTOR,
HAMSTRING,
QUADRICEPS,
ABDUCTORS,
CALVES,
GLUTEAL,
HEAD,
NECK
```
> Changed muscle groups for feedback

- mobile/components/JoinedProgramCard.js
- mobile/components/JoinedProgramDetail.js
- mobile/package-lock.json
- mobile/package.json
Feature
Users can't rate a program they joined.
Users can rate a program in JoinedProgramDetail page. Connection with backend is established.
> Add rating for mobile

- frontend/src/components/FeedbackModal.component.jsx
- frontend/src/components/ProgramFeedCard.component.jsx
- frontend/src/components/TrainerFeedbackModal.component.jsx
- frontend/src/components/TrainerProgramCard.component.jsx
- frontend/src/components/profilePage.component.jsx
- frontend/src/constants/feedbackMuscles.js
- frontend/src/context/FeedbackContext.jsx
This PR introduces a comprehensive feedback system enabling users to provide muscle-specific feedback on training programs and trainers to view organized feedback through an interactive 3D model interface.
- 🎯 Interactive 3D muscle model for targeted feedback
- 📝 Multi-muscle feedback submission system
- 👥 Dedicated trainer feedback overview
- ⚡ Real-time visual feedback
- 🔄 Efficient data management with React Query
Users cannot provide specific feedback for different muscle groups in training programs, and trainers lack a systematic way to view participant feedback.
- Select muscles via 3D model
- Add multiple muscle-specific feedbacks
- Real-time visual highlighting
- Form validation with error handling
- Comprehensive feedback overview
- Grouped by muscle
- 3D model visualization
- …
> added feedback and display page

- frontend/src/components/searchPage.component.jsx
- package-lock.json
Feature enhancement and bug fix for the exercise search functionality. This PR introduces a comprehensive muscle mapping system to improve search accuracy and user experience.
Currently, the search functionality uses strict matching between the body highlighter muscles and exercise database muscles. This leads to:
- Missed exercises due to muscle name variations (e.g., "TRAPS" vs "TRAPEZIUS")
- No grouping of related muscles
- Inconsistent muscle name display
- Limited search results when clicking on the body model
Link to issue: [Updated Search Page for Better Muscle Group Mapping and Search Functionality](https://github.com/bounswe/bounswe2024group7/issues/335)
The new implementation:
1. Maps all exercise database muscles to their corresponding body highlighter muscles
2. Groups related …
> fixed the bug in search

- frontend/src/components/ProgressGraphs.component.jsx
- frontend/src/components/profilePage.component.jsx
Now both Trainer and Trainee can view the Progress Graphs
> Now both Trainer and Trainee can view the Progress Graphs

- backend/demo-group7/src/test/java/com/group7/demo/ExerciseServiceTest.java
Implemented unit tests for the `ExerciseService` class.
- **Purpose**: Verify that all exercises are retrieved from the `ExerciseRepository`.
- **Validation**: Ensures the repository's `findAll()` method is called and the returned list is not null or empty.
- **Purpose**: Test the behavior of `getExercise` when a valid ID is provided.
- **Validation**: Confirms the retrieved exercise matches the expected ID.
- **Purpose**: Ensure an `EntityNotFoundException` is thrown when an invalid exercise ID is provided.
- **Validation**: Validate that the exception message includes the exercise ID.
- **Purpose**: Test `getUserExerciseProgress` when valid exercise tracking data is available.
- **Validation**: Verifies the progress is correctly calculated by summing completed sets and grouping them by …
> Implemented unit test for Exercise Service

- backend/demo-group7/src/test/java/com/group7/demo/PostControllerTest.java
9 of 9 tests are passing for PostController
Implemented unit tests
> Added 9 tests for Post endpoints and 9 passes
